// src/components/core/Button.tsx
import React from "react";

// Utils
import { classNames } from "@purpled/utils";

export default function Button(
  { children, className, ...rest }:
  { children: React.ReactNode; className?: string }
) {
  return (
    <button
      className={classNames(
        className,
        "group relative inline-block box-content",
        "font-serif font-medium text-sm tracking-widester uppercase",
        "text-gray-900",
        // "text-gray-300 border border-gray-300 px-6 py-1.5 rounded-full hover:bg-gray-300 hover:text-black transition-colors cursor-pointer"
      )}
      {...rest}
    >
      <span
        className={classNames(
          "block bg-gray-200 h-6 w-12 group-hover:w-full transition-all",
          "absolute left-0 top-1/2 -translate-y-1/2 z-0"
        )}
      ></span>
      <span className="px-4 block relative z-10 text-gray-900">{children}</span>
      <span
        className={classNames(
          "block bg-purple-700 h-3 w-3 -mr-1.5 rounded-full",
          "absolute right-full top-1/2 transform -translate-y-1/2 z-0"
        )}
      ></span>
    </button>
  );
}

// src/lib/components/Button.svelte
<script>
	let { children, ...props } = $props();
</script>

<button
	{...props}
	class="relative m-3 inline-block min-w-[200px] cursor-pointer overflow-visible border-2 border-shade py-4 font-serif text-sm leading-none font-medium tracking-[2px] text-black uppercase transition-colors duration-300"
>
	<!-- class="relative m-3 inline-block min-w-[200px] cursor-pointer overflow-visible border-2 border-shade py-5 font-sans text-xs leading-none font-medium tracking-[3.6px] text-black uppercase transition-colors duration-300" -->
	{@render children()}
	<span>
		<span class="[&>span]:absolute [&>span]:h-6 [&>span]:w-0.5">
			<span class="top-full right-full bg-gradient-to-b from-shade to-transparent"></span>
			<span class="top-full left-full bg-gradient-to-b from-shade to-transparent"></span>
			<span class="right-full bottom-full bg-gradient-to-t from-shade to-transparent"></span>
			<span class="bottom-full left-full bg-gradient-to-t from-shade to-transparent"></span>
		</span>

		<span class="[&>span]:absolute [&>span]:h-0.5 [&>span]:w-6">
			<span class="top-full right-full bg-gradient-to-l from-shade to-transparent"></span>
			<span class="right-full bottom-full bg-gradient-to-l from-shade to-transparent"></span>
			<span class="top-full left-full bg-gradient-to-r from-shade to-transparent"></span>
			<span class="bottom-full left-full bg-gradient-to-r from-shade to-transparent"></span>
		</span>
	</span>
</button>
